export class Denuncia {
    anonima:number;
    codigo:string;
    nombre:string ;
    apellido_paterno:string ;
    apellido_materno:string ;
    sexo:number ;
    edad:number ;
    correo:string ;
    lada:number ;
    telefono:number ;
    ext:number ;
    cp_persona:number ;
    estado_persona:number ;
    municipio_persona:number ;
    localidad_persona:number ;
    colonia_persona:string ;
    calle_persona:string ;
    ext_persona:string ;
    int_persona:string ;
    tipo_denuncia:number ;
    razon_social:string ;
    giro:string ;
    producto:string ;
    estado_denuncia:number ;
    municipio_denuncia:number ;
    calle_denuncia:string ;
    ext_denuncia:string ;
    cp_denuncia:number ;
    colonia_denuncia:string ;
    narracion:string ;
    catalogo_entidad_persona:any;
}
